AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Calculator Lambda container app

Resources:
  CalculatorAPI:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      FunctionName: CalculatorFunction
      Timeout: 10
      MemorySize: 128
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /calc
            Method: POST
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calc"
